// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkO_0tUHfxLEL0Jrt_rAEbMT6XehWs1lU',
    appId: '1:55279927718:web:a0e6d12264d0f330830f67',
    messagingSenderId: '55279927718',
    projectId: 'chat-app-898e6',
    authDomain: 'chat-app-898e6.firebaseapp.com',
    storageBucket: 'chat-app-898e6.appspot.com',
    measurementId: 'G-N726FPYNYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDOmB-eBWpv0ep38Bpbjo1nCD4qftGtw',
    appId: '1:55279927718:android:0353bf080c8f9e9b830f67',
    messagingSenderId: '55279927718',
    projectId: 'chat-app-898e6',
    storageBucket: 'chat-app-898e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw5Bylr9G-UuxDyq12r8I9wV8uCSIYuhQ',
    appId: '1:55279927718:ios:85f6762a2a391dbd830f67',
    messagingSenderId: '55279927718',
    projectId: 'chat-app-898e6',
    storageBucket: 'chat-app-898e6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw5Bylr9G-UuxDyq12r8I9wV8uCSIYuhQ',
    appId: '1:55279927718:ios:2618ce4bd201649d830f67',
    messagingSenderId: '55279927718',
    projectId: 'chat-app-898e6',
    storageBucket: 'chat-app-898e6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
